#
# GraphDB Dockerfile
#
# https://github.com/dockerfile/mongodb
#
FROM neo4j:latest

#EXPOSE 7473 7474 7687
#VOLUME [/data /logs /var/lib/neo4j/import /startup /plugins]
#WORKDIR /var/lib/neo4j
#ENTRYPOINT ["tini" "-g" "--" "/startup/docker-entrypoint.sh"]	
#CMD ["neo4j"]