version: '3.4'

services:

  mystore.store:
    container_name: mystore.store    
    image: ${DOCKER_REGISTRY-}mystore.store
    restart: always  
    depends_on:
     - mystore.mongo
     - mystore.api
     - mystore.identity    
    networks:      
      - mystore    

  mystore.support:
    container_name: mystore.support
    image: ${DOCKER_REGISTRY-}mystore.support
    restart: always  
    depends_on:
     - mystore.mongo
     - mystore.api    
     - mystore.identity    
    networks:      
      - mystore

  mystore.proxy:
    container_name: mystore.proxy
    image: ${DOCKER_REGISTRY-}mystore.proxy
    restart: always  
    depends_on:
     - mystore.store
     - mystore.support
     - mystore.identity
     - mystore.api
    networks:      
      - mystore

  mystore.identity:
    container_name: mystore.identity
    image: ${DOCKER_REGISTRY-}mystore.identity
    restart: always  
    depends_on:
     - mystore.mongo
    networks:      
      - mystore

  mystore.api:
    container_name: mystore.api   
    image: ${DOCKER_REGISTRY-}mystore.api
    restart: always  
    depends_on:
     - mystore.identity
     - mystore.mongo
    networks:
      - mystore

  mystore.mongo:
    container_name: mystore.mongo
    image: ${DOCKER_REGISTRY-}mystore.mongo
    restart: always  
    networks: 
      - mystore

networks:  
    mystore: