version: '3.4'

services:

  store.mystore.local:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  support.mystore.local:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  proxy.mystore.local:  
    ports:
      - "80:80"
      - "443:443"   
      - "27017:27017"   
      
  identity.mystore.local:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  api.mystore.local:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  mongo.mystore.local:
    environment: 
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=admin
      - MONGO_INITDB_DATABASE=admin        
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init-local.js:ro
      - ${APPDATA}/MongoDb/Data:/data/db
      - ${APPDATA}/MongoDb/Logs:/var/log/mongodb/