version: '3.4'

services:

  store.mystore.local:
    container_name: store.mystore.local
    hostname: store.mystore.local
    image: ${DOCKER_REGISTRY-}store.mystore.local

    build:
      context: .
      dockerfile: Store/Dockerfile  
    depends_on:
     - mongo.mystore.local
     - api.mystore.local
     - identity.mystore.local    
    networks:      
      - mystore    

  support.mystore.local:
    container_name: support.mystore.local
    hostname: support.mystore.local
    image: ${DOCKER_REGISTRY-}support.mystore.local
    build:
      context: .
      dockerfile: Support/Dockerfile    
    depends_on:
     - mongo.mystore.local
     - api.mystore.local    
     - identity.mystore.local    
    networks:      
      - mystore

  proxy.mystore.local:
    container_name: proxy.mystore.local
    hostname: mystore.local    
    image: ${DOCKER_REGISTRY-}proxy.mystore.local
    build:
      context: .
      dockerfile: Proxy/Dockerfile
    restart: always  
    depends_on:
     - store.mystore.local
     - support.mystore.local
     - identity.mystore.local
     - api.mystore.local
    networks:      
      - mystore

  identity.mystore.local:
    container_name: identity.mystore.local
    hostname: identity.mystore.local
    image: ${DOCKER_REGISTRY-}identity.mystore.local
    build:
      context: .
      dockerfile: Identity/Dockerfile
    restart: always  
    depends_on:
     - mongo.mystore.local
    networks:      
      - mystore

  api.mystore.local:
    container_name: api.mystore.local
    hostname: api.mystore.local
    image: ${DOCKER_REGISTRY-}api.mystore.local
    build:
      context: .
      dockerfile: Api/Dockerfile
    restart: always  
    depends_on:
     - identity.mystore.local
     - mongo.mystore.local
    networks:
      - mystore

  mongo.mystore.local:
    container_name: ${DOCKER_REGISTRY-}mongo.mystore.local
    hostname: mongo.mystore.local
    image: ${DOCKER_REGISTRY-}mongo.mystore.local
    build:
      context: .
      dockerfile: MongoDB/Dockerfile
    restart: always  
    networks: 
      - mystore

networks:  
    mystore: