version: '3.4'

services:
  # certificates must support these dns hostname's
  # referto the section :ConfigureSecrets in Proxy/Gen-Certs.cmd regarding UserSecrets
  store:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 

  support:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 
 
  proxy:  
    environment:
      - PROXY_DOMAIN=${APP_DOMAIN}
      - NGINX_ENVSUBST_OUTPUT_DIR=${NGINX_ENVSUBST_OUTPUT_DIR}

  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 

  mongo:
    environment: 
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_STORAGE_USERNAME=${MONGO_STORAGE_USERNAME}
      - MONGO_STORAGE_PASSWORD=${MONGO_STORAGE_PASSWORD}
    volumes:
      #
      # initlisation script for empty mongo data folder (NOTE This is written by configuration script)
      #
      - ./MongoDb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      #
      # local persistence of mongo database (Note this is created by Configuration script)
      #
      - ${APPDATA}/MongoDb/Data:/data/db 
      - ${APPDATA}/MongoDb/Logs:/var/log/mongodb

  graph:
    environment:
      - e NEO4J_AUTH${NEO4J_CREDENTIALS}  
    volumes:
      - ${APPDATA}/GraphDb/Data:/data
      - ${APPDATA}/GraphDb/Logs:/logs
