version: '3.4'

services:
  # certificates must support these dns hostname's
  # referto the section :ConfigureSecrets in Proxy/Gen-Certs.cmd regarding UserSecrets
  store:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 

  support:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 
 
  proxy:  
    environment:
      - PROXY_DOMAIN=${APP_DOMAIN}
      - NGINX_ENVSUBST_OUTPUT_DIR=${NGINX_ENVSUBST_OUTPUT_DIR}

  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 

  mongo:
    environment: 
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_STORAGE_USERNAME=${MONGO_STORAGE_USERNAME}
      - MONGO_STORAGE_PASSWORD=${MONGO_STORAGE_PASSWORD}
    volumes:
      #
      # initlisation script for empty mongo data folder (NOTE This is written by configuration script)
      #
      - ./MongoDb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      #
      # local persistence of mongo database (Note this is created by Configuration script)
      #
      - ${APPDATA}/MongoDb/Data:/data/db 
      - ${APPDATA}/MongoDb/Logs:/var/log/mongodb

  graph:
    environment:
      - NEO4J_AUTH${NEO4J_CREDENTIALS}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_pagecache_size=512m
      - NEO4J_dbms_default__advertised__address=graph.${APP_DOMAIN}
      - NEO4J_dbms_ssl_policy_bolt_enabled=true
      - NEO4J_dbms_ssl_policy_bolt_base__directory=certificates/bolt
      - NEO4J_dbms_ssl_policy_bolt_private__key=myHost.key
      - NEO4J_dbms_ssl_policy_bolt_myHost__certificate=myHost.crt
      - NEO4J_dbms_ssl_policy_bolt_client__auth=NONE
      - NEO4J_dbms_connector_bolt_tls__level=REQUIRED
      - NEO4J_dbms_connector_https_enabled=true
      - NEO4J_dbms_ssl_policy_https_enabled=true
      - NEO4J_dbms_ssl_policy_https_base__directory=certificates/https
      - NEO4J_dbms_ssl_policy_https_myHost__key=myHost.key
      - NEO4J_dbms_ssl_policy_https_myHost__certificate=myHost.crt
      - NEO4J_dbms_ssl_policy_https_client__auth=NONE
    volumes:
      - ${APPDATA}/GraphDb/Data:/data
      - ${APPDATA}/GraphDb/Logs:/logs
      - ${APPDATA}/GraphDb/ssl:/ssl
