version: '3.4'

services:
  # certificates must support these dns hostname's
  # referto the section :ConfigureSecrets in Proxy/Gen-Certs.cmd regarding UserSecrets
  myInfo.store:
    hostname: store.local.myInfo.world 
    build:
      context: .
      dockerfile: Store/Dockerfile  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 

  myInfo.support:
    hostname: support.local.myInfo.world 
    build:
      context: .
      dockerfile: Support/Dockerfile    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 

  myInfo.proxy:  
    hostname: local.myInfo.world
    build:
      context: .
      dockerfile: Proxy/Dockerfile
    ports:
      - "80:80"
      - "443:443"   
      - "27017:27017"   
      
  myInfo.identity:
    hostname: identity.local.myInfo.world
    build:
      context: .
      dockerfile: Identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 

  myInfo.api:
    hostname: api.local.myInfo.world 
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 

  myInfo.mongo:
    hostname: mongo.local.myInfo.world 
    build:
      context: .
      dockerfile: MongoDB/Dockerfile
    environment: 
        # NOTE: these must currently match mongo-init-local.js settings
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=admin
      - MONGO_INITDB_DATABASE=admin
      #- MONGO_STORAGE_USERNAME=storage
      #- MONGO_STORAGE_PASSWORD=storagepass
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      # local persistence of mongo database
      - ${APPDATA}/Microsoft/UserSecrets/5151c09A-27d2-4f8a-a445-ea3ae9b6e786:/root/usersecrets:ro 
      - ${APPDATA}/MongoDb/Data:/data/db 
      - ${APPDATA}/MongoDb/Logs:/var/log/mongodb/