version: '3.4'

services:

  mystore.store:
    hostname: store.mystore.local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  mystore.support:
    hostname: support.mystore.local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  mystore.proxy:  
    hostname: mystore.local    
    ports:
      - "80:80"
      - "443:443"   
      - "27017:27017"   
      
  mystore.identity:
    hostname: identity.mystore.local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  mystore.api:
    hostname: api.mystore.local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  mystore.mongo:
    hostname: mongo.mystore.local
    environment: 
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=admin
      - MONGO_INITDB_DATABASE=admin        
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init-local.js:ro
      - ${APPDATA}/MongoDb/Data:/data/db
      - ${APPDATA}/MongoDb/Logs:/var/log/mongodb/