version: '3.4'

services:
  store.mystore.local:
    container_name: store.mystore.local
    hostname: store.mystore.local
    image: ${DOCKER_REGISTRY-}store.mystore.local

    build:
      context: .
      dockerfile: WebApp1/Dockerfile  
    networks:      
      - mystore    

  support.mystore.local:
    container_name: support.mystore.local
    hostname: support.mystore.local
    image: ${DOCKER_REGISTRY-}support.mystore.local
    build:
      context: .
      dockerfile: WebApp2/Dockerfile        
    networks:      
      - mystore

  proxy.mystore.local:
    container_name: proxy.mystore.local
    hostname: proxy.mystore.local    
    image: ${DOCKER_REGISTRY-}support.mystore.local
    build:
      context: ./Proxy
      dockerfile: Dockerfile        
    depends_on:
     - store.mystore.local
     - support.mystore.local
    networks:      
      - mystore
networks:  
    mystore: