version: '3.4'

services:

  myInfo.store:
    container_name: myInfo.store    
    image: ${DOCKER_REGISTRY-}myinfo.store:${TAG:-latest}
    restart: always  
    depends_on:
     - myInfo.mongo
     - myInfo.api
     - myInfo.identity    
    networks:      
      - myInfo    

  myInfo.support:
    container_name: myInfo.support
    image: ${DOCKER_REGISTRY-}myinfo.support:${TAG:-latest}
    restart: always  
    depends_on:
     - myInfo.mongo
     - myInfo.api    
     - myInfo.identity    
    networks:      
      - myInfo

  myInfo.proxy:
    container_name: myInfo.proxy
    image: ${DOCKER_REGISTRY-}myinfo.proxy:${TAG:-latest}
    restart: always  
    depends_on:
     - myInfo.store
     - myInfo.support
     - myInfo.identity
     - myInfo.api
    networks:      
      - myInfo

  myInfo.identity:
    container_name: myInfo.identity
    image: ${DOCKER_REGISTRY-}myinfo.identity:${TAG:-latest}
    restart: always  
    depends_on:
     - myInfo.mongo
    networks:      
      - myInfo

  myInfo.api:
    container_name: myInfo.api   
    image: ${DOCKER_REGISTRY-}myinfo.api:${TAG:-latest}
    restart: always  
    depends_on:
     - myInfo.identity
     - myInfo.mongo
    networks:
      - myInfo

  myInfo.mongo:
    container_name: myInfo.mongo
    image: ${DOCKER_REGISTRY-}myinfo.mongo:${TAG:-latest}
    restart: always  
    networks: 
      - myInfo

networks:  
    myInfo: